In [ ]:
import numpy as np

data = np.array([[4, 8, 13, 7],
                 [6, 2, 3, 15]])

num_rows, num_cols = data.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

mean_vector = np.mean(data, axis=1)
print("\nMean Vector:")
print(mean_vector)

centered_data = data - mean_vector[:, np.newaxis]
print("\nCentered Data:")
for row in centered_data:
    print(row)

covariance_matrix = np.cov(centered_data)
print("\nCovariance Matrix:")
for row in covariance_matrix:
    print(row)

eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

sorted_indices = np.argsort(eigen_values)[::-1]
eigen_values = eigen_values[sorted_indices]
eigen_vectors = eigen_vectors[:, sorted_indices]

print("\nEigen Values:")
for i, value in enumerate(eigen_values, 1):
    print(f"lambda_{i}: {value}")

print("\nEigen Vectors:")
for vector in eigen_vectors.T:
    print(vector)

first_principal_component = eigen_vectors[:, 0]
second_principal_component = eigen_vectors[:, 1]

projected_data_first = np.dot(first_principal_component, centered_data)
projected_data_second = np.dot(second_principal_component, centered_data)
print("\nNew Values:")
print(projected_data_first)
print(projected_data_second)


Number of rows: 2
Number of columns: 4

Mean Vector:
[8.  6.5]

Centered Data:
[-4.  0.  5. -1.]
[-0.5 -4.5 -3.5  8.5]

Covariance Matrix:
[14. -8.]
[-8. 35.]

Eigen Values:
lambda_1: 37.70037878244408
lambda_2: 11.299621217555917

Eigen Vectors:
[ 0.31981892 -0.94747869]
[-0.94747869 -0.31981892]

New Values:
[-0.80553633  4.26365409  4.91526999 -8.37338775]
[ 3.9498242   1.43918513 -3.61802722 -1.77098211]


In [22]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

data = pd.read_csv("https://raw.githubusercontent.com/PrerakPatel13/Sem_5_Practs/main/dataset/Mall_Customers.csv")

data = data.drop(columns=["CustomerID", "Genre"])

centered_data = data - data.mean()

covariance_matrix = centered_data.cov()

eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

sorted_indices = np.argsort(eigen_values)[::-1]
eigen_values = eigen_values[sorted_indices]
eigen_vectors = eigen_vectors[:, sorted_indices]

print("\nCentered Data:")
print(centered_data)

print("\nCovariance Matrix:")
print(covariance_matrix)

print("\nEigen Values:")
for i, value in enumerate(eigen_values, 1):
    print(f"lambda_{i}: {value}")

print("\nEigen Vectors:")
print(eigen_vectors)

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

pca = PCA(n_components=3)
principal_components = pca.fit_transform(scaled_data)

print("\nNew Values:")
for i in range(200):
    print(f"PC1: {principal_components[i, 0]}, PC2: {principal_components[i, 1]}, PC3: {principal_components[i, 2]}")




Centered Data:
       Age  Annual Income (k$)  Spending Score (1-100)
0   -19.85              -45.56                   -11.2
1   -17.85              -45.56                    30.8
2   -18.85              -44.56                   -44.2
3   -15.85              -44.56                    26.8
4    -7.85              -43.56                   -10.2
..     ...                 ...                     ...
195  -3.85               59.44                    28.8
196   6.15               65.44                   -22.2
197  -6.85               65.44                    23.8
198  -6.85               76.44                   -32.2
199  -8.85               76.44                    32.8

[200 rows x 3 columns]

Covariance Matrix:
                               Age  Annual Income (k$)  Spending Score (1-100)
Age                     195.133166           -4.548744             -118.040201
Annual Income (k$)       -4.548744          689.835578                6.716583
Spending Score (1-100) -118.040201         